; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28008.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Pablo\AppData\Local\Temp\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
